"""Tag taxonomy for qgis-mcp, derived from the server's own section headers.

Single source of truth for the fastmcp Visibility API. `escape` and
`verify` carry the escape hatches and the screenshot, so every preset must
include them or an agent is stranded with no way back.
"""

TOOL_TAGS = {
    'add_annotation': 'annotations',
    'add_bookmark': 'canvas',
    'add_db_layer': 'database',
    'add_feature': 'features',
    'add_field': 'features',
    'add_layer_action': 'layers',
    'add_layer_join': 'data',
    'add_layout_item': 'layouts',
    'add_layout_page': 'layouts',
    'add_map_decoration': 'annotations',
    'add_raster_layer': 'layers',
    'add_relation': 'data',
    'add_vector_layer': 'layers',
    'add_wms_layer': 'layers',
    'algorithm_help': 'processing',
    'apply_map_theme': 'canvas',
    'apply_style_from_file': 'styling',
    'buffer': 'geoprocessing',
    'calculate_statistics': 'analysis',
    'centroid': 'geoprocessing',
    'check_data_integrity': 'verify',
    'check_layer_health': 'verify',
    'check_topology': 'verify',
    'clear_annotations': 'annotations',
    'clear_selection': 'features',
    'clip': 'geoprocessing',
    'convex_hull': 'geoprocessing',
    'count_features': 'analysis',
    'create_grid': 'geoprocessing',
    'create_layout': 'layouts',
    'create_map_theme': 'canvas',
    'create_memory_layer': 'layers',
    'create_new_project': 'project',
    'delete_bookmark': 'canvas',
    'delete_features': 'features',
    'delete_field': 'features',
    'delete_layout': 'layouts',
    'delete_map_theme': 'canvas',
    'diagnose_crs': 'verify',
    'difference': 'geoprocessing',
    'disable_plugin': 'settings',
    'dissolve': 'geoprocessing',
    'duplicate_layer': 'layers',
    'edit_feature': 'features',
    'enable_plugin': 'settings',
    'execute_code': 'escape',
    # set_toolset MUST carry a tag every preset includes: an untagged tool
    # is filtered out by enable(only=True), which would strand the session
    # in a narrow preset with no way to widen it again.
    'set_toolset': 'escape',
    'execute_processing': 'escape',
    'execute_sql': 'database',
    'export_atlas': 'layouts',
    'export_dxf': 'layouts',
    'export_layer': 'io',
    'export_layout_image': 'layouts',
    'export_layout_pdf': 'layouts',
    'export_layout_svg': 'layouts',
    'find_layer': 'layers',
    'get_canvas_info': 'canvas',
    'get_canvas_screenshot': 'canvas',
    'get_db_table_info': 'database',
    'get_layer_extent': 'layers',
    'get_layer_features': 'layers',
    'get_layer_fields': 'layers',
    'get_layer_info': 'layers',
    'get_layer_note': 'layers',
    'get_layer_style': 'styling',
    'get_layers': 'layers',
    'get_map_tip': 'layers',
    'get_mesh_info': 'layers',
    'get_message_log': 'canvas',
    'get_point_cloud_info': 'layers',
    'get_project_info': 'project',
    'get_project_variables': 'project',
    'get_qgis_info': 'project',
    'get_raster_info': 'raster',
    'get_raster_statistics': 'raster',
    'get_selected_features': 'features',
    'get_settings': 'settings',
    'get_snapping_config': 'settings',
    'get_undo_stack': 'editing',
    'group_layers': 'layers',
    'heatmap': 'geoprocessing',
    'import_and_add_layer': 'io',
    'import_idml': 'layouts',
    'intersection': 'geoprocessing',
    'join_by_location': 'geoprocessing',
    'layer_diff': 'verify',
    'list_algorithms': 'processing',
    'list_annotations': 'annotations',
    'list_bookmarks': 'canvas',
    'list_db_connections': 'database',
    'list_db_tables': 'database',
    'list_layer_actions': 'layers',
    'list_layer_joins': 'data',
    'list_layouts': 'layouts',
    'list_map_themes': 'canvas',
    'list_plugins': 'settings',
    'list_processing_providers': 'processing',
    'list_relations': 'data',
    'list_style_presets': 'styling',
    'list_supported_formats': 'io',
    'load_project': 'project',
    'measure_geodesic': 'verify',
    'measure_geometry': 'analysis',
    'merge_layers': 'geoprocessing',
    'ping': 'project',
    'random_points': 'geoprocessing',
    'redo': 'editing',
    'refresh_canvas': 'canvas',
    'remove_layer': 'layers',
    'remove_layer_action': 'layers',
    'remove_layer_join': 'data',
    'remove_layer_labels': 'labeling',
    'remove_layout_item': 'layouts',
    'remove_relation': 'data',
    'rename_layer': 'layers',
    'render_map': 'canvas',
    'reorder_layers': 'layers',
    'reproject': 'geoprocessing',
    'save_project': 'project',
    'save_style_to_file': 'styling',
    'screenshot': 'verify',
    'select_by_expression': 'features',
    'select_by_location': 'features',
    'set_atlas': 'layouts',
    'set_canvas_extent': 'canvas',
    'set_color_ramp': 'styling',
    'set_data_defined_property': 'labeling',
    'set_field_widget': 'forms',
    'set_form_config': 'forms',
    'set_layer_color': 'styling',
    'set_layer_filter': 'features',
    'set_layer_labels': 'labeling',
    'set_layer_note': 'layers',
    'set_layer_opacity': 'layers',
    'set_layer_style': 'styling',
    'set_layer_temporal': 'temporal',
    'set_layer_visibility': 'layers',
    'set_layout_item_dd_property': 'layouts',
    'set_layout_item_property': 'layouts',
    'set_map_overview': 'layouts',
    'set_map_theme_for_item': 'layouts',
    'set_map_tip': 'layers',
    'set_project_crs': 'canvas',
    'set_project_variable': 'project',
    'set_raster_brightness_contrast': 'raster',
    'set_raster_renderer': 'raster',
    'set_rotation': 'canvas',
    'set_rule_based_labels': 'labeling',
    'set_scale': 'canvas',
    'set_settings': 'settings',
    'set_snapping_config': 'settings',
    'set_temporal_range': 'temporal',
    'simplify': 'geoprocessing',
    'spatial_query': 'analysis',
    'transform_coordinates': 'verify',
    'undo': 'editing',
    'union': 'geoprocessing',
    'update_field_values': 'features',
    'validate_expression': 'verify',
    'validate_geometry': 'verify',
    'validate_wkt': 'verify',
    'verify_operation': 'verify',
    'verify_project': 'verify',
    'voronoi': 'geoprocessing',
    'zoom_in': 'canvas',
    'zoom_out': 'canvas',
    'zoom_to_bookmark': 'canvas',
    'zoom_to_extent': 'canvas',
    'zoom_to_full_extent': 'canvas',
    'zoom_to_layer': 'layers',
}

PRESETS = {
    'full': None,  # sentinel: everything
    'cartography': {'io', 'styling', 'canvas', 'escape', 'layers', 'layouts', 'project', 'verify', 'labeling'},
    'data': {'io', 'escape', 'database', 'analysis', 'layers', 'forms', 'project', 'features', 'verify', 'data'},
    'geoprocess': {'escape', 'geoprocessing', 'raster', 'layers', 'verify', 'project', 'features', 'processing', 'analysis'},
    'minimal': {'escape', 'verify', 'layers', 'project'},
}


def preset_tags(preset):
    return PRESETS.get(preset)
